name: Deployment to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Running SSH actions
        uses: appleboy/ssh-action@master
        env:
          DOT_ENV: ${{ secrets.DOT_ENV_PRODUCTION }}
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          envs: DOCROOT,REPO_URL,DOT_ENV_PRODUCTION
          script: |
          git -C $DOCROOT reset --hard
          git -C $DOCROOT pull || git clone --single-branch --branch main $REPO_URL $DOCROOT
          envsubst > ${DOCROOT}/.env < ${DOCROOT}/.env.example
          composer install --working-dir $DOCROOT
          php -f ${DOCROOT}